"""create code units

Revision ID: f3784f4a7b7e
Revises: 
Create Date: 2026-09-17 22:36:01.895692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3784f4a7b7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_units',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('unit_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_units_file_path'), 'code_units', ['file_path'], unique=False)
    op.create_index(op.f('ix_code_units_language'), 'code_units', ['language'], unique=False)
    op.create_index(op.f('ix_code_units_name'), 'code_units', ['name'], unique=False)
    op.create_index(op.f('ix_code_units_repository'), 'code_units', ['repository'], unique=False)
    op.create_index(op.f('ix_code_units_unit_type'), 'code_units', ['unit_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_units_unit_type'), table_name='code_units')
    op.drop_index(op.f('ix_code_units_repository'), table_name='code_units')
    op.drop_index(op.f('ix_code_units_name'), table_name='code_units')
    op.drop_index(op.f('ix_code_units_language'), table_name='code_units')
    op.drop_index(op.f('ix_code_units_file_path'), table_name='code_units')
    op.drop_table('code_units')
    # ### end Alembic commands ###
